export const rowData: any[] = [
  
    {
        "CandidateID": 7830,
        "FullName": "Bryn Burbank",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": "(289) 123-4567",
        "City": "TORONTO",
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-31T17:01:24.993",
        "LastUpdate": "2023-08-31T17:01:24.993",
        "Available": null,
        "Email": "test@gmail.com",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": null,
        "AccountManager": " ",
        "Ownership": "Candidate Registration",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": null,
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": "M5A 4S7",
        "Latitude": 43.653275,
        "Longitude": -79.369178,
        "Age": null,
        "YearsOfExperience": 0,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Candidate Registration",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": null,
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": false,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7829,
        "FullName": "Justin McNamara",
        "Title": "Sales Representative",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "TORONTO",
        "PresentEmployer": "CBRE",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-29T17:40:47.26",
        "LastUpdate": "2023-08-29T17:40:55.637",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Western University",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 7,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-29T17:40:51.993",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7828,
        "FullName": "Satadru Mukherjee PMP® CSM®",
        "Title": "PM",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": null,
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-28T19:47:35.72",
        "LastUpdate": "2023-08-28T19:47:44.83",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Indian Institute of Technology, Kharagpur",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": null,
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 13,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-28T19:47:41.127",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7827,
        "FullName": "Adam Kleinert",
        "Title": "Senior Solutions Architect",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": null,
        "PresentEmployer": "Vena Solutions",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-24T19:52:19.587",
        "LastUpdate": "2023-08-24T19:52:26.493",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Scrum Alliance",
        "ClientID": 0,
        "EducationLevel": "TRAINING",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 7,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-24T19:52:22.603",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7826,
        "FullName": "Linda Mindscope",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": "(416) 286-9098",
        "City": null,
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-18T11:51:39.163",
        "LastUpdate": "2023-08-18T16:58:09",
        "Available": null,
        "Email": "linda.test1@mindcope.com",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "Indeed",
        "AccountManager": " ",
        "Ownership": "Candidate Registration",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": null,
        "Comment": "Applied to Job: 1940 Java Developer",
        "LastPlacement": null,
        "LastJobOrder": " [Job ID: 1940] - Java Developer",
        "Country": "Canada",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 0,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Candidate Registration",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-18T11:55:46.407",
        "BusinessPhone": null,
        "CellPhone": "(416) 286-9098",
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7825,
        "FullName": "Conor Fennell",
        "Title": "Commercial Director",
        "Status": "Off Limits",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "TORONTO",
        "PresentEmployer": "McLean & Company",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-17T16:13:55.12",
        "LastUpdate": "2023-08-29T17:28:55.803",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Research Council",
        "ClientID": 0,
        "EducationLevel": "TRAINING",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 11,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-17T16:14:03.65",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#BD2029",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7824,
        "FullName": "Billy McPhee",
        "Title": "Sales Director",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": null,
        "PresentEmployer": "Colligo",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-10T16:21:08.233",
        "LastUpdate": "2023-08-10T16:21:15.78",
        "Available": null,
        "Email": "bmcphee@colligo.com",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Queen's University",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": null,
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 8,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-10T16:21:11.343",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7823,
        "FullName": "Denis Covic",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "HAMILTON",
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-10T15:35:19.803",
        "LastUpdate": "2023-08-10T15:35:19.803",
        "Available": "2023-08-10T00:00:00",
        "Email": "denis.covic@mindscope.com",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "Other",
        "AccountManager": "Mindscope Support",
        "Ownership": "Mindscope Support",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": null,
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": "L8G 5J2",
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 0,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Mindscope Support",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-10T15:35:48.997",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7822,
        "FullName": "Jordan Griffiths",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "VANCOUVER",
        "PresentEmployer": "Process E.I.T. WSP",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-10T15:06:20.497",
        "LastUpdate": "2023-08-10T15:07:21.56",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": "TRAINING",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "British Columbia",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 7,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-10T15:06:27.903",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7821,
        "FullName": "Jack Allford",
        "Title": "Recruitment Specialist - Testing",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "HOUSTON",
        "PresentEmployer": "Avetix Group",
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-02T14:10:08.403",
        "LastUpdate": "2023-08-02T14:10:15.24",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Doncaster College",
        "ClientID": 0,
        "EducationLevel": "college",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "United States",
        "ProvinceState": "Texas",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 14,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-02T14:10:11.537",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7820,
        "FullName": "Fatmata Dulleh",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "Holland",
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-08-01T16:33:30.223",
        "LastUpdate": "2023-08-01T16:33:30.35",
        "Available": null,
        "Email": "fatmatad286@gmail.com",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": null,
        "AccountManager": " ",
        "Ownership": "System Administrator",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": "unknown",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Belgium",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 3,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "System Administrator",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-08-01T16:33:33.907",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7818,
        "FullName": "Tony Xu",
        "Title": "Valuation Control Associate",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "West Conshohocken",
        "PresentEmployer": "Morgan Stanley",
        "PresentEmployerID": null,
        "EnteredDate": "2023-07-25T18:13:23.6",
        "LastUpdate": "2023-07-25T18:13:23.85",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": null,
        "AccountManager": " ",
        "Ownership": "System Administrator",
        "Rank": null,
        "Institution": "University of Delaware",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "United States",
        "ProvinceState": "Pennsylvania",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 9,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "System Administrator",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-07-25T18:13:28.367",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7817,
        "FullName": "Shannon Warren",
        "Title": "Founder",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": "+1 866 666-9520",
        "City": null,
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-07-18T19:21:00.36",
        "LastUpdate": "2023-07-18T19:21:08.767",
        "Available": null,
        "Email": "Shannon@matrixhr.ca",
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": "unknown",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 20,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-07-18T19:21:05.283",
        "BusinessPhone": null,
        "CellPhone": "+1 866 666-9520",
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7816,
        "FullName": "Michael Hobbs",
        "Title": "IT manager",
        "Status": "Available",
        "SecondStatus": null,
        "Division": "I.T.",
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": "I.T.",
        "Office": "Branch",
        "DefaultPhone": "657 456 321",
        "City": "Richmond Hill",
        "PresentEmployer": "Webbers Tech",
        "PresentEmployerID": 330,
        "EnteredDate": "2023-05-31T19:34:08.733",
        "LastUpdate": "2023-06-01T12:59:22.61",
        "Available": "2023-05-31T00:00:00",
        "Email": "JHobbs@gmail.com",
        "LastContacted": "2023-05-30T00:00:00",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": "Excellent",
        "MarketingSource": "LinkedIn",
        "AccountManager": "Lucas Tari",
        "Ownership": "Lucas Tari",
        "Rank": null,
        "Institution": "University of Toronto",
        "ClientID": 0,
        "EducationLevel": "Masters",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": "L4C0G3",
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 22,
        "BaseSalary": "90000.00",
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Lucas Tari",
        "Bonus": "10000.00",
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-05-31T19:37:37.483",
        "BusinessPhone": null,
        "CellPhone": "657 456 321",
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": "Direct-Hire",
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": 1012,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7815,
        "FullName": "Kaylee Heart",
        "Title": "Nurse",
        "Status": "Available",
        "SecondStatus": null,
        "Division": "Internal Medicine",
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": "Hospitalist",
        "Office": "Branch",
        "DefaultPhone": "416 567 890",
        "City": "Richmond Hill",
        "PresentEmployer": "Northside Medical",
        "PresentEmployerID": 329,
        "EnteredDate": "2023-05-31T18:57:15.057",
        "LastUpdate": "2023-07-17T14:23:58.09",
        "Available": "2023-06-01T00:00:00",
        "Email": "KayleeHeart@gmail.com",
        "LastContacted": "2023-07-17T14:23:57.163",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": "Excellent",
        "MarketingSource": "LinkedIn",
        "AccountManager": "Lucas Tari",
        "Ownership": "Lucas Tari",
        "Rank": null,
        "Institution": "Ryerson University",
        "ClientID": 0,
        "EducationLevel": "Masters",
        "Comment": "I called the applicant to discuss nurse position...\r\n",
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": "L4C0G7",
        "Latitude": null,
        "Longitude": null,
        "Age": 33,
        "YearsOfExperience": 1,
        "BaseSalary": "20000.00",
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Lucas Tari",
        "Bonus": "0.00",
        "ADPFileNumber": null,
        "NewestResumeCreated": null,
        "BusinessPhone": null,
        "CellPhone": "416 567 890",
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": "Temp/Contract",
        "SourceName": null,
        "IsUploadedOriginalResume": false,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": 1020,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7813,
        "FullName": "Shayna Hayes",
        "Title": "VP, Compliance and Supprt Services",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "OTTAWA",
        "PresentEmployer": "Hybrid",
        "PresentEmployerID": 324,
        "EnteredDate": "2023-05-29T15:09:27.993",
        "LastUpdate": "2023-05-29T15:09:32.463",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Algonquin College of Applied Arts and Technology",
        "ClientID": 0,
        "EducationLevel": "college",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 9,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-05-29T15:09:31.76",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7812,
        "FullName": "Yasir Qureshi",
        "Title": "Software Project Manager",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": null,
        "PresentEmployer": "DNAstack",
        "PresentEmployerID": 323,
        "EnteredDate": "2023-05-25T15:07:07.01",
        "LastUpdate": "2023-05-25T15:07:11.777",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": "unknown",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": " [Job ID: 2413] - Senior Technical Developer ",
        "Country": null,
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 6,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-05-25T15:07:10.98",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7811,
        "FullName": "Avi Weiss",
        "Title": "Legal Counsel",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "TORONTO",
        "PresentEmployer": "Coinsquare",
        "PresentEmployerID": 321,
        "EnteredDate": "2023-05-19T14:09:55.38",
        "LastUpdate": "2023-05-19T14:09:58.507",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "York University",
        "ClientID": 0,
        "EducationLevel": "TRAINING",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 7,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-05-19T14:09:58.053",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7810,
        "FullName": "Ken Spangenberg",
        "Title": "Chief Sales Officer",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": null,
        "PresentEmployer": "AWRE Sports",
        "PresentEmployerID": 318,
        "EnteredDate": "2023-05-01T14:47:50.003",
        "LastUpdate": "2023-05-01T14:47:53.363",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Arcadia University",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "United States",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 13,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-05-01T14:47:53.033",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7809,
        "FullName": "Ashley Johnson",
        "Title": "Partner manager",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "New York",
        "PresentEmployer": "Genesys",
        "PresentEmployerID": 317,
        "EnteredDate": "2023-04-27T18:09:46.073",
        "LastUpdate": "2023-04-27T18:09:50.527",
        "Available": null,
        "Email": null,
        "LastContacted": null,
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Ivey",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": null,
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "United States",
        "ProvinceState": "New York",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 10,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-04-27T18:09:50.103",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7807,
        "FullName": "Dr. James Smith",
        "Title": null,
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": "(333) 444-5858 ",
        "City": null,
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-04-20T17:28:53.147",
        "LastUpdate": "2023-04-20T18:35:51.297",
        "Available": null,
        "Email": "bryn.a.burbank@gmail.com",
        "LastContacted": "2023-04-20T18:36:03.767",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "Cold call",
        "AccountManager": "Bryn Burbank",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": null,
        "ClientID": 0,
        "EducationLevel": null,
        "Comment": "Remember to call these PMs\r\n",
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": null,
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 0,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": null,
        "BusinessPhone": "(333) 444-5858 ",
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": false,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": false,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7805,
        "FullName": "Tyson Jerry",
        "Title": "Account Manager",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "Columbia",
        "PresentEmployer": "Renewable Gas",
        "PresentEmployerID": 311,
        "EnteredDate": "2023-04-06T17:15:10.3",
        "LastUpdate": "2023-04-20T18:35:51.297",
        "Available": null,
        "Email": null,
        "LastContacted": "2023-04-20T18:36:03.75",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Ivey",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": "Remember to call these PMs\r\n",
        "LastPlacement": null,
        "LastJobOrder": " [Job ID: 2413] - Senior Technical Developer ",
        "Country": "United States",
        "ProvinceState": "South Carolina",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 15,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-04-06T17:15:25.94",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7804,
        "FullName": "Georgia McClelland",
        "Title": "Senior Associate",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": "(289) 879-0759 ",
        "City": "VANCOUVER",
        "PresentEmployer": "Korn Ferry",
        "PresentEmployerID": 302,
        "EnteredDate": "2023-03-23T17:12:59.493",
        "LastUpdate": "2023-04-20T18:41:11.703",
        "Available": null,
        "Email": null,
        "LastContacted": "2023-04-20T18:41:11.703",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "The University of British Columbia",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": "Remember to call these PMs\r\n",
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "British Columbia",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 6,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-03-23T17:13:01.21",
        "BusinessPhone": null,
        "CellPhone": "(289) 879-0759 ",
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7803,
        "FullName": "Rabi Motiwala",
        "Title": "Director - Risk and Compliance Practise",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "LONDON",
        "PresentEmployer": "Trestle Group Ventures",
        "PresentEmployerID": 301,
        "EnteredDate": "2023-03-23T14:28:29.46",
        "LastUpdate": "2023-04-20T18:35:51.297",
        "Available": null,
        "Email": null,
        "LastContacted": "2023-04-20T18:36:03.687",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Middlesex University",
        "ClientID": 0,
        "EducationLevel": "university",
        "Comment": "Remember to call these PMs\r\n",
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "United Kingdom",
        "ProvinceState": null,
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 11,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-03-23T14:28:31.757",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    },
    {
        "CandidateID": 7802,
        "FullName": "Natalie O'Hearn",
        "Title": "Project Implementation Coordinator",
        "Status": "Available",
        "SecondStatus": null,
        "Division": null,
        "PresentEmployerDivisionID": null,
        "IsClientLink": true,
        "Department": null,
        "Office": null,
        "DefaultPhone": null,
        "City": "TORONTO",
        "PresentEmployer": null,
        "PresentEmployerID": null,
        "EnteredDate": "2023-03-13T17:43:37.287",
        "LastUpdate": "2023-04-20T18:35:51.297",
        "Available": null,
        "Email": null,
        "LastContacted": "2023-04-20T18:36:03.657",
        "ExpireDate": null,
        "ListModifiedDate": "2023-09-05T17:21:16.317",
        "MemberLocalStatus": null,
        "Rating": null,
        "MarketingSource": "LinkedIn",
        "AccountManager": " ",
        "Ownership": "Bryn Burbank",
        "Rank": null,
        "Institution": "Seneca College",
        "ClientID": 0,
        "EducationLevel": "college",
        "Comment": "Remember to call these PMs\r\n",
        "LastPlacement": null,
        "LastJobOrder": null,
        "Country": "Canada",
        "ProvinceState": "Ontario",
        "ZipPostalCode": null,
        "Latitude": null,
        "Longitude": null,
        "Age": null,
        "YearsOfExperience": 13,
        "BaseSalary": null,
        "LastSalaryIncrease": null,
        "TotalCompensation": null,
        "EnteredBy": "Bryn Burbank",
        "Bonus": null,
        "ADPFileNumber": null,
        "NewestResumeCreated": "2023-03-13T17:43:39.49",
        "BusinessPhone": null,
        "CellPhone": null,
        "OfflimitsExpiryDate": null,
        "MemberFlag": null,
        "Region": null,
        "MinimumPayRate": null,
        "OvertimePayRate": null,
        "Unsubscribed": null,
        "SpecialID": null,
        "NPN": null,
        "Color": "#3C8F32",
        "BusinessUnit": null,
        "SourceName": null,
        "IsUploadedOriginalResume": true,
        "EntryYear": null,
        "IsAppended": false,
        "FirstPlacementStartDate": null,
        "CustomField1": null,
        "CustomField2": null,
        "CustomField3": null,
        "CustomField4": null,
        "CustomField5": null,
        "CustomField6": null,
        "CustomField7": null,
        "CustomField8": null,
        "CustomField9": null,
        "CustomField10": null,
        "CustomField11": null,
        "CustomField12": null,
        "CustomField13": null,
        "CustomField14": null,
        "CustomField15": null,
        "CustomField16": null,
        "CustomField17": null,
        "CustomField18": null,
        "CustomField19": null,
        "CustomField20": null,
        "IsProfileViewed": false,
        "IsRejectedFromWorkSpace": false,
        "IsRejected": false,
        "RejectedFrom": "",
        "IsCandidateLink": true,
        "DivisionID": null,
        "CustomUserList1": " ",
        "CustomUserList2": " ",
        "CustomUserList3": " "
    }

  ];
  